Homework 1
Katsiaryna-Ledak/Ekaterina_Khudzhamkulova pull request #1
Opened 2021-08-04 06:13 UTC by Katsiaryna-Ledak

Automated testing lab EPAM
Selenium block
Homework 1
1st pull request

2021-08-04 16:11 UTC, komyagin requested changes

2021-08-04 16:11 UTC, komyagin commented on .idea/workspace.xml
>      <option name="autoReloadType" value="SELECTIVE" />
This directory must be excluded and added to the .gitignore file

2021-08-04 17:16 UTC, Katsiaryna-Ledak commented on .idea/workspace.xml
>      <option name="autoReloadType" value="SELECTIVE" />
I've corrected the .gitignore file.

2021-08-05 07:31 UTC, komyagin approved these changes

2021-08-05 07:54 UTC, merged