Homework 7 (JDI)
Katsiaryna-Ledak/Ekaterina_Khudzhamkulova pull request #8
Opened 2021-08-26 12:48 UTC by Katsiaryna-Ledak

2021-09-01 16:21 UTC, pnatashap requested changes
Comments in code

2021-09-01 16:21 UTC, pnatashap commented on src/test/resources/HW3.properties
>  userName = Roman
Should not be a part of this PR

2021-09-01 16:21 UTC, pnatashap commented on src/test/resources/testng/ex1Ex2HW4.xml
> +
Should not be a part of this PR

2021-09-01 16:21 UTC, pnatashap commented on src/test/resources/testng/ex1Ex2HW6.xml
> +  <test name="ex1Ex2HW6Test">
Should not be a part of this PR

2021-09-01 16:21 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/tests/BaseTest.java
> +        homePage.checkOpened();
Test is failed on MaterialAndMetals page open if login is failed. 
We should fail on login

2021-09-02 07:08 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw3/pages/HomePage.java
> +
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:08 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/pages/AbstractPage.java
> +    protected WebDriver webDriver;
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:09 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/pages/DifferentElementsPage.java
> +public class DifferentElementsPage extends AbstractPage {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:09 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/pages/HomePage.java
> +public class HomePage extends AbstractPage {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:09 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/pages/LoginPanelComponent.java
> +public class LoginPanelComponent extends AbstractPage {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:09 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/steps/Exercise1Steps.java
> +public class Exercise1Steps {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:09 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/steps/Exersice2Steps.java
> +public class Exersice2Steps {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:10 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/testcases/DifferentElementsPageTC.java
> +public class DifferentElementsPageTC extends InitializationTest {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:10 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/testcases/HomePageTC.java
> +public class HomePageTC extends InitializationTest {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:10 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/testcases/InitializationTest.java
> +public class InitializationTest {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:10 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/util/AttachmentUtils.java
> +public class AttachmentUtils {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:10 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/util/PropertiesFileReader.java
> +public class PropertiesFileReader {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:11 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/pages/DifferentElementsPage.java
> +public class DifferentElementsPage extends AbstractPage {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:11 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/pages/HomePage.java
> +public class HomePage extends AbstractPage {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:11 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/pages/LoginPanelComponent.java
> +public class LoginPanelComponent extends AbstractPage {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:11 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/steps/Exercise1Steps.java
> +public class Exercise1Steps {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:11 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/steps/Exersice2Steps.java
> +public class Exersice2Steps {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:11 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/testcases/DifferentElementsPageTC.java
> +public class DifferentElementsPageTC extends InitializationTest {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:12 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/testcases/HomePageTC.java
> +public class HomePageTC extends InitializationTest {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:12 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/util/AttachmentUtils.java
> +public class AttachmentUtils {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:12 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/util/PropertiesFileReader.java
> +public class PropertiesFileReader {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:12 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/util/driver/WebDriverFactory.java
> +public class WebDriverFactory {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:13 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/util/driver/WebDriverSingleton.java
> +public class WebDriverSingleton {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:13 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw6/util/driver/WebDriverTypeException.java
> +public class WebDriverTypeException extends RuntimeException {
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:13 UTC, Katsiaryna-Ledak commented on src/test/resources/testng/ex1Ex2HW4.xml
> +
After rebase with master this comment is marked as 'outdated'

2021-09-02 07:14 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw4/listeners/ScreenshotListener.java
> +public class ScreenshotListener implements ITestListener {
After rebase with master this comment is marked as 'outdated'

2021-09-02 12:39 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw7/tests/BaseTest.java
> +        homePage.checkOpened();
Resolved in commit:https://github.com/Katsiaryna-Ledak/Ekaterina_Khudzhamkulova/pull/8/commits/e01eb318d1b38ea5a4432e348a944597702841da

2021-09-02 12:39 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw7/tests/BaseTest.java
> +        openSite(JdiTestingSite.class);
Resolved in commit:https://github.com/Katsiaryna-Ledak/Ekaterina_Khudzhamkulova/pull/8/commits/e01eb318d1b38ea5a4432e348a944597702841da

2021-09-02 12:39 UTC, Katsiaryna-Ledak commented on src/test/java/com/epam/tc/hw7/dataproviders/UserData.java
> +            u.password = "Jdi1234";
Resolved in commit:https://github.com/Katsiaryna-Ledak/Ekaterina_Khudzhamkulova/pull/8/commits/e01eb318d1b38ea5a4432e348a944597702841da

2021-09-10 20:11 UTC, pnatashap approved these changes
There are two comments, it's better to check the best practices for these situations

2021-09-10 20:11 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/tests/BaseTest.java
> +        homePage.logout();
What is the reason to logout if we kill the browser after?

2021-09-10 20:11 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/dataproviders/MetalsColorsDataProvider.java
> +        String jsonText = IOUtils.toString(fileInputStream, StandardCharsets.UTF_8.name());
It's not a good practice to read content, Gson can be used with Reader.

2021-09-11 13:30 UTC, merged